spring.application.name=Digital Banking API
server.port=8080
# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/digital_banking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# LOGGING SQL
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# JACKSON
# ===============================
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# ===============================
# JWT (sẽ dùng ở bước Security)
# ===============================
jwt.secret=YourSuperSecretKeyForDigitalBankingAPIReplaceLater123456789
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
